[2025-02-15T02:20:37.960+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_ETL.export_weather_alerts manual__2025-02-15T00:56:13.638531+00:00 [queued]>
[2025-02-15T02:20:37.977+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_ETL.export_weather_alerts manual__2025-02-15T00:56:13.638531+00:00 [queued]>
[2025-02-15T02:20:37.979+0000] {taskinstance.py:1331} INFO - Starting attempt 4 of 4
[2025-02-15T02:20:38.003+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): export_weather_alerts> on 2025-02-15 00:56:13.638531+00:00
[2025-02-15T02:20:38.010+0000] {standard_task_runner.py:57} INFO - Started process 519 to run task
[2025-02-15T02:20:38.016+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'weather_data_ETL', 'export_weather_alerts', 'manual__2025-02-15T00:56:13.638531+00:00', '--job-id', '106', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpqmiwwkr4']
[2025-02-15T02:20:38.020+0000] {standard_task_runner.py:85} INFO - Job 106: Subtask export_weather_alerts
[2025-02-15T02:20:38.162+0000] {task_command.py:410} INFO - Running <TaskInstance: weather_data_ETL.export_weather_alerts manual__2025-02-15T00:56:13.638531+00:00 [running]> on host cbea98f91475
[2025-02-15T02:20:38.400+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airscholar' AIRFLOW_CTX_DAG_ID='weather_data_ETL' AIRFLOW_CTX_TASK_ID='export_weather_alerts' AIRFLOW_CTX_EXECUTION_DATE='2025-02-15T00:56:13.638531+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-15T00:56:13.638531+00:00'
[2025-02-15T02:20:38.441+0000] {logging_mixin.py:149} INFO - Index(['sender_name', 'location_id', 'event', 'start', 'end', 'description'], dtype='object')
[2025-02-15T02:20:38.455+0000] {logging_mixin.py:149} INFO - Data inserted successfully!
[2025-02-15T02:20:38.457+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-02-15T02:20:38.482+0000] {taskinstance.py:1368} INFO - Marking task as SUCCESS. dag_id=weather_data_ETL, task_id=export_weather_alerts, execution_date=20250215T005613, start_date=20250215T022037, end_date=20250215T022038
[2025-02-15T02:20:38.552+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-02-15T02:20:38.608+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
