[2025-02-15T01:56:40.787+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_ETL.export_hourly_forecast manual__2025-02-15T00:56:13.638531+00:00 [queued]>
[2025-02-15T01:56:40.803+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_ETL.export_hourly_forecast manual__2025-02-15T00:56:13.638531+00:00 [queued]>
[2025-02-15T01:56:40.804+0000] {taskinstance.py:1331} INFO - Starting attempt 2 of 2
[2025-02-15T01:56:40.822+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): export_hourly_forecast> on 2025-02-15 00:56:13.638531+00:00
[2025-02-15T01:56:40.831+0000] {standard_task_runner.py:57} INFO - Started process 116 to run task
[2025-02-15T01:56:40.837+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'weather_data_ETL', 'export_hourly_forecast', 'manual__2025-02-15T00:56:13.638531+00:00', '--job-id', '87', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpjdenlv1t']
[2025-02-15T01:56:40.843+0000] {standard_task_runner.py:85} INFO - Job 87: Subtask export_hourly_forecast
[2025-02-15T01:56:40.984+0000] {task_command.py:410} INFO - Running <TaskInstance: weather_data_ETL.export_hourly_forecast manual__2025-02-15T00:56:13.638531+00:00 [running]> on host cbea98f91475
[2025-02-15T01:56:41.228+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airscholar' AIRFLOW_CTX_DAG_ID='weather_data_ETL' AIRFLOW_CTX_TASK_ID='export_hourly_forecast' AIRFLOW_CTX_EXECUTION_DATE='2025-02-15T00:56:13.638531+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-15T00:56:13.638531+00:00'
[2025-02-15T01:56:41.286+0000] {logging_mixin.py:149} INFO - Index(['dt', 'temp', 'feels_like', 'pressure', 'humidity', 'dew_point',
       'clouds', 'uvi', 'wind_speed', 'wind_gust', 'pop', 'rain_1h', 'snow_1h',
       'main', 'description', 'location_id', 'current_weather_id'],
      dtype='object')
[2025-02-15T01:56:41.308+0000] {logging_mixin.py:149} INFO - Error inserting data: insert or update on table "hourly_forecast" violates foreign key constraint "hourly_forecast_current_weather_id_fkey"
DETAIL:  Key (current_weather_id)=(15) is not present in table "current_weather".
[2025-02-15T01:56:41.310+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-02-15T01:56:41.335+0000] {taskinstance.py:1368} INFO - Marking task as SUCCESS. dag_id=weather_data_ETL, task_id=export_hourly_forecast, execution_date=20250215T005613, start_date=20250215T015640, end_date=20250215T015641
[2025-02-15T01:56:41.377+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-02-15T01:56:41.420+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
