[2025-02-15T00:24:37.911+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_ETL.export_current_weather manual__2025-02-15T00:15:20.628188+00:00 [queued]>
[2025-02-15T00:24:37.926+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_ETL.export_current_weather manual__2025-02-15T00:15:20.628188+00:00 [queued]>
[2025-02-15T00:24:37.927+0000] {taskinstance.py:1331} INFO - Starting attempt 4 of 4
[2025-02-15T00:24:37.944+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): export_current_weather> on 2025-02-15 00:15:20.628188+00:00
[2025-02-15T00:24:37.952+0000] {standard_task_runner.py:57} INFO - Started process 1217 to run task
[2025-02-15T00:24:37.955+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'weather_data_ETL', 'export_current_weather', 'manual__2025-02-15T00:15:20.628188+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpvj4azqew']
[2025-02-15T00:24:37.958+0000] {standard_task_runner.py:85} INFO - Job 63: Subtask export_current_weather
[2025-02-15T00:24:38.059+0000] {task_command.py:410} INFO - Running <TaskInstance: weather_data_ETL.export_current_weather manual__2025-02-15T00:15:20.628188+00:00 [running]> on host 2079ceed134c
[2025-02-15T00:24:38.222+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airscholar' AIRFLOW_CTX_DAG_ID='weather_data_ETL' AIRFLOW_CTX_TASK_ID='export_current_weather' AIRFLOW_CTX_EXECUTION_DATE='2025-02-15T00:15:20.628188+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-15T00:15:20.628188+00:00'
[2025-02-15T00:24:38.253+0000] {logging_mixin.py:149} INFO - Index(['dt', 'temp', 'feels_like', 'pressure', 'humidity', 'dew_point',
       'clouds', 'uvi', 'wind_speed', 'wind_gust', 'rain_1h', 'snow_1h',
       'main', 'description', 'location_id'],
      dtype='object')
[2025-02-15T00:24:38.278+0000] {logging_mixin.py:149} INFO - Error inserting data: there is no unique or exclusion constraint matching the ON CONFLICT specification
[2025-02-15T00:24:38.279+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-02-15T00:24:38.297+0000] {taskinstance.py:1368} INFO - Marking task as SUCCESS. dag_id=weather_data_ETL, task_id=export_current_weather, execution_date=20250215T001520, start_date=20250215T002437, end_date=20250215T002438
[2025-02-15T00:24:38.330+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-02-15T00:24:38.365+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
