[2025-02-14T06:29:09.549+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_current_weather.load_data_from_api scheduled__2025-02-13T00:00:00+00:00 [queued]>
[2025-02-14T06:29:09.563+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_current_weather.load_data_from_api scheduled__2025-02-13T00:00:00+00:00 [queued]>
[2025-02-14T06:29:09.564+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-02-14T06:29:09.585+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): load_data_from_api> on 2025-02-13 00:00:00+00:00
[2025-02-14T06:29:09.597+0000] {standard_task_runner.py:57} INFO - Started process 37 to run task
[2025-02-14T06:29:09.607+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'get_current_weather', 'load_data_from_api', 'scheduled__2025-02-13T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/weather_data_dag.py', '--cfg-path', '/tmp/tmphoutkm2f']
[2025-02-14T06:29:09.614+0000] {standard_task_runner.py:85} INFO - Job 17: Subtask load_data_from_api
[2025-02-14T06:29:09.831+0000] {task_command.py:410} INFO - Running <TaskInstance: get_current_weather.load_data_from_api scheduled__2025-02-13T00:00:00+00:00 [running]> on host 52ab0d44335c
[2025-02-14T06:29:10.161+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airscholar' AIRFLOW_CTX_DAG_ID='get_current_weather' AIRFLOW_CTX_TASK_ID='load_data_from_api' AIRFLOW_CTX_EXECUTION_DATE='2025-02-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-13T00:00:00+00:00'
[2025-02-14T06:29:10.358+0000] {logging_mixin.py:149} INFO - Error fetching weather data: 
response: <Response [401]>
url: http://api.openweathermap.org/data/2.5/weather?lat=39.87652886804281&lon=-105.76577005628859&appid=None
[2025-02-14T06:29:10.435+0000] {logging_mixin.py:149} INFO - Error fetching weather data: 
response: <Response [401]>
url: http://api.openweathermap.org/data/2.5/weather?lat=39.49367530426312&lon=-106.15941614917506&appid=None
[2025-02-14T06:29:10.511+0000] {logging_mixin.py:149} INFO - Error fetching weather data: 
response: <Response [401]>
url: http://api.openweathermap.org/data/2.5/weather?lat=39.93747528686545&lon=-105.58400897925249&appid=None
[2025-02-14T06:29:10.586+0000] {logging_mixin.py:149} INFO - Error fetching weather data: 
response: <Response [401]>
url: http://api.openweathermap.org/data/2.5/weather?lat=40.466202977197106&lon=-106.78094073252413&appid=None
[2025-02-14T06:29:10.681+0000] {logging_mixin.py:149} INFO - Error fetching weather data: 
response: <Response [401]>
url: http://api.openweathermap.org/data/2.5/weather?lat=39.19114916529031&lon=-120.2557470349228&appid=None
[2025-02-14T06:29:10.759+0000] {logging_mixin.py:149} INFO - Error fetching weather data: 
response: <Response [401]>
url: http://api.openweathermap.org/data/2.5/weather?lat=45.293131560098956&lon=-111.36294562989895&appid=None
[2025-02-14T06:29:11.048+0000] {logging_mixin.py:149} INFO - Error fetching weather data: 
response: <Response [401]>
url: http://api.openweathermap.org/data/2.5/weather?lat=39.25671866393303&lon=-120.13341133625593&appid=None
[2025-02-14T06:29:11.134+0000] {logging_mixin.py:149} INFO - Error fetching weather data: 
response: <Response [401]>
url: http://api.openweathermap.org/data/2.5/weather?lat=46.934754314303206&lon=-121.48384975195034&appid=None
[2025-02-14T06:29:11.209+0000] {logging_mixin.py:149} INFO - Error fetching weather data: 
response: <Response [401]>
url: http://api.openweathermap.org/data/2.5/weather?lat=43.594634283058724&lon=-110.84610943388475&appid=None
[2025-02-14T06:29:11.287+0000] {logging_mixin.py:149} INFO - Error fetching weather data: 
response: <Response [401]>
url: http://api.openweathermap.org/data/2.5/weather?lat=39.478861079038985&lon=-106.07839392176015&appid=None
[2025-02-14T06:29:11.468+0000] {logging_mixin.py:149} INFO - Error fetching weather data: 
response: <Response [401]>
url: http://api.openweathermap.org/data/2.5/weather?lat=39.619779887440146&lon=-106.36957399501661&appid=None
[2025-02-14T06:29:11.604+0000] {logging_mixin.py:149} INFO - Error fetching weather data: 
response: <Response [401]>
url: http://api.openweathermap.org/data/2.5/weather?lat=43.110007073773104&lon=-72.91026718465827&appid=None
[2025-02-14T06:29:11.681+0000] {logging_mixin.py:149} INFO - Error fetching weather data: 
response: <Response [401]>
url: http://api.openweathermap.org/data/2.5/weather?lat=50.073500220248334&lon=-122.95937601933981&appid=None
[2025-02-14T06:29:11.764+0000] {logging_mixin.py:149} INFO - Error fetching weather data: 
response: <Response [401]>
url: http://api.openweathermap.org/data/2.5/weather?lat=45.96980068114292&lon=6.879032518531963&appid=None
[2025-02-14T06:29:11.825+0000] {python.py:183} INFO - Done. Returned value was: Empty DataFrame
Columns: [pass, resort, date, vis, temp, feels_like, temp_min, temp_max, weather, weather_description, cloud_percent, wind_speed, latitude, longitude, rain_3h_mm, rain_1h_mm, snow_1h_mm, snow_3h_mm]
Index: []
[2025-02-14T06:29:12.126+0000] {taskinstance.py:1368} INFO - Marking task as SUCCESS. dag_id=get_current_weather, task_id=load_data_from_api, execution_date=20250213T000000, start_date=20250214T062909, end_date=20250214T062912
[2025-02-14T06:29:12.199+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-02-14T06:29:12.252+0000] {taskinstance.py:2674} INFO - 1 downstream tasks scheduled from follow-on schedule check
